name: Update Ollama Models

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 00:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  update-models:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Copy Python scripts
        run: |
          mkdir -p scripts
          cp ref/update_models0.py scripts/
          cp ref/update_models.py scripts/
          cp ref/allinone.py scripts/

      - name: Run update script
        run: |
          cd scripts
          python allinone.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          if [[ -n $(git status -s) ]]; then
            git add public/data/ollama-models*.json
            git commit -m "chore: update models data [skip ci]"
            git push
          fi
